/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    wisata: Wisata;
    kuliner: Kuliner;
    akomodasi: Akomodasi;
    sejarah: Sejarah;
    tokoh: Tokoh;
    terdekat: Terdekat;
    blog: Blog;
    'profil-desa': ProfilDesa;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    wisata: WisataSelect<false> | WisataSelect<true>;
    kuliner: KulinerSelect<false> | KulinerSelect<true>;
    akomodasi: AkomodasiSelect<false> | AkomodasiSelect<true>;
    sejarah: SejarahSelect<false> | SejarahSelect<true>;
    tokoh: TokohSelect<false> | TokohSelect<true>;
    terdekat: TerdekatSelect<false> | TerdekatSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'profil-desa': ProfilDesaSelect<false> | ProfilDesaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wisata".
 */
export interface Wisata {
  id: number;
  judul: string;
  slug: string;
  subKategori: 'jelajah-alam' | 'outdoor-activity' | 'aktivitas-keluarga' | 'spot-foto';
  featured?: boolean | null;
  tagline?: string | null;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  deskripsi: string;
  lokasi: {
    namaTempat: string;
    alamat: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  hargaTiket?: string | null;
  jamBuka?: string | null;
  rating?: number | null;
  fasilitas?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kuliner".
 */
export interface Kuliner {
  id: number;
  judul: string;
  slug: string;
  subKategori: 'open-now' | 'wajib-coba' | 'cafe-resto';
  featured?: boolean | null;
  tagline?: string | null;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  deskripsi: string;
  lokasi: {
    namaTempat: string;
    alamat: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  jamBuka: string;
  jamTutup: string;
  hargaKisaran: string;
  menuFavorit?:
    | {
        namaMenu: string;
        harga?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "akomodasi".
 */
export interface Akomodasi {
  id: number;
  judul: string;
  slug: string;
  subKategori: 'villa-resort' | 'camping-ground';
  featured?: boolean | null;
  tagline?: string | null;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  deskripsi: string;
  lokasi: {
    namaTempat: string;
    alamat: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  hargaPerMalam: string;
  kapasitas?: string | null;
  kontakBooking?: {
    whatsapp?: string | null;
    telepon?: string | null;
    bookingUrl?: string | null;
  };
  fasilitas?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sejarah".
 */
export interface Sejarah {
  id: number;
  judul: string;
  slug: string;
  era: string;
  featured?: boolean | null;
  ringkasan: string;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  deskripsi: string;
  lokasi: {
    namaTempat: string;
    alamat: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  faktaMenarik?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokoh".
 */
export interface Tokoh {
  id: number;
  nama: string;
  slug: string;
  peran: string;
  featured?: boolean | null;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  ringkasanBio: string;
  biografiLengkap: string;
  lokasi: {
    namaTempat: string;
    alamat: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  kontribusi?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terdekat".
 */
export interface Terdekat {
  id: number;
  judul: string;
  slug: string;
  kategori: 'danau-air' | 'petualangan-rafting' | 'curug-alam' | 'taman-rekreasi';
  jarakWaktu: string;
  tipeTrip: string;
  featured?: boolean | null;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  tagline?: string | null;
  deskripsi: string;
  lokasi: {
    namaTempat: string;
    alamat: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  ruteAkses?: string | null;
  hargaTiket?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  judul: string;
  slug: string;
  kategori: 'cerita-feature' | 'kegiatan-pengumuman' | 'tips-wisata';
  featured?: boolean | null;
  penulis: string;
  publishedAt?: string | null;
  waktuBaca?: string | null;
  foto?: (number | null) | Media;
  fotoUrl?: string | null;
  ringkasan: string;
  konten: string;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profil-desa".
 */
export interface ProfilDesa {
  id: number;
  namaDesa: string;
  ringkasanUmum: string;
  sejarahDesa?: string | null;
  sumberResmi?: {
    portalBestieBogor?: string | null;
    situsResmiDesaId?: string | null;
  };
  statistik?: {
    jumlahPenduduk?: number | null;
    jumlahKk?: number | null;
    luasWilayahKm2?: number | null;
    ketinggianMeter?: number | null;
    jumlahRt?: number | null;
    jumlahRw?: number | null;
  };
  apbdesRingkasan?: {
    tahunAnggaran?: string | null;
    totalPendapatan?: string | null;
    totalBelanja?: string | null;
  };
  kontakKantor?: {
    alamat?: string | null;
    telepon?: string | null;
    email?: string | null;
    jamLayanan?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'wisata';
        value: number | Wisata;
      } | null)
    | ({
        relationTo: 'kuliner';
        value: number | Kuliner;
      } | null)
    | ({
        relationTo: 'akomodasi';
        value: number | Akomodasi;
      } | null)
    | ({
        relationTo: 'sejarah';
        value: number | Sejarah;
      } | null)
    | ({
        relationTo: 'tokoh';
        value: number | Tokoh;
      } | null)
    | ({
        relationTo: 'terdekat';
        value: number | Terdekat;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'profil-desa';
        value: number | ProfilDesa;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wisata_select".
 */
export interface WisataSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  subKategori?: T;
  featured?: T;
  tagline?: T;
  foto?: T;
  fotoUrl?: T;
  deskripsi?: T;
  lokasi?:
    | T
    | {
        namaTempat?: T;
        alamat?: T;
        latitude?: T;
        longitude?: T;
      };
  hargaTiket?: T;
  jamBuka?: T;
  rating?: T;
  fasilitas?:
    | T
    | {
        item?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kuliner_select".
 */
export interface KulinerSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  subKategori?: T;
  featured?: T;
  tagline?: T;
  foto?: T;
  fotoUrl?: T;
  deskripsi?: T;
  lokasi?:
    | T
    | {
        namaTempat?: T;
        alamat?: T;
        latitude?: T;
        longitude?: T;
      };
  jamBuka?: T;
  jamTutup?: T;
  hargaKisaran?: T;
  menuFavorit?:
    | T
    | {
        namaMenu?: T;
        harga?: T;
        id?: T;
      };
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "akomodasi_select".
 */
export interface AkomodasiSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  subKategori?: T;
  featured?: T;
  tagline?: T;
  foto?: T;
  fotoUrl?: T;
  deskripsi?: T;
  lokasi?:
    | T
    | {
        namaTempat?: T;
        alamat?: T;
        latitude?: T;
        longitude?: T;
      };
  hargaPerMalam?: T;
  kapasitas?: T;
  kontakBooking?:
    | T
    | {
        whatsapp?: T;
        telepon?: T;
        bookingUrl?: T;
      };
  fasilitas?:
    | T
    | {
        item?: T;
        id?: T;
      };
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sejarah_select".
 */
export interface SejarahSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  era?: T;
  featured?: T;
  ringkasan?: T;
  foto?: T;
  fotoUrl?: T;
  deskripsi?: T;
  lokasi?:
    | T
    | {
        namaTempat?: T;
        alamat?: T;
        latitude?: T;
        longitude?: T;
      };
  faktaMenarik?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokoh_select".
 */
export interface TokohSelect<T extends boolean = true> {
  nama?: T;
  slug?: T;
  peran?: T;
  featured?: T;
  foto?: T;
  fotoUrl?: T;
  ringkasanBio?: T;
  biografiLengkap?: T;
  lokasi?:
    | T
    | {
        namaTempat?: T;
        alamat?: T;
        latitude?: T;
        longitude?: T;
      };
  kontribusi?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terdekat_select".
 */
export interface TerdekatSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  kategori?: T;
  jarakWaktu?: T;
  tipeTrip?: T;
  featured?: T;
  foto?: T;
  fotoUrl?: T;
  tagline?: T;
  deskripsi?: T;
  lokasi?:
    | T
    | {
        namaTempat?: T;
        alamat?: T;
        latitude?: T;
        longitude?: T;
      };
  ruteAkses?: T;
  hargaTiket?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  kategori?: T;
  featured?: T;
  penulis?: T;
  publishedAt?: T;
  waktuBaca?: T;
  foto?: T;
  fotoUrl?: T;
  ringkasan?: T;
  konten?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profil-desa_select".
 */
export interface ProfilDesaSelect<T extends boolean = true> {
  namaDesa?: T;
  ringkasanUmum?: T;
  sejarahDesa?: T;
  sumberResmi?:
    | T
    | {
        portalBestieBogor?: T;
        situsResmiDesaId?: T;
      };
  statistik?:
    | T
    | {
        jumlahPenduduk?: T;
        jumlahKk?: T;
        luasWilayahKm2?: T;
        ketinggianMeter?: T;
        jumlahRt?: T;
        jumlahRw?: T;
      };
  apbdesRingkasan?:
    | T
    | {
        tahunAnggaran?: T;
        totalPendapatan?: T;
        totalBelanja?: T;
      };
  kontakKantor?:
    | T
    | {
        alamat?: T;
        telepon?: T;
        email?: T;
        jamLayanan?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}